#!/usr/bin/env zsh


setup_environment(){
    PYTHON_PATH=${HOME}/.local/bin
###    IGNORE_ERRORS=E221,E701,E202
                    }

main(){
    setup_environment
    which pyflakes > /dev/null || exit 254
    which pycodestyle > /dev/null || exit 254
    pyflakes $*
    pycodestyle --ignore=$IGNORE_ERRORS --repeat $*
    exit 0
}

main $*
